### ISSUE TITLE
[question] where do you store files for micropress?

### ISSUE THREAD

**Issue by Juev** [glushchenko/glushchenko.github.io#1]
Hello,

As I can see, this repository contained only one branch: master, where placed only files for website.
Where you store files for micropress generator? Why you dont use separate branches for it? And why you dont use travis for generation your site and for deployng it to GitHub Pages?

**Comment by glushchenko** [comment]
Hi, i'm use GitHub just as html hosting. Blog generated at local computer, markdown files are stored local too. No vendor locks – no problems.

In my opinion Travis CI big overhead for blog. Generated content delivered over git commits perfectly. I can switch any time to S3 or deliver content over ssh, it's part on my control.

**Comment by Juev** [comment]
Overhead? I dont think so. Because if you setup one time blog generation on travis, you can change delivery option to another location. It's very simple. 

For example, my site generated on travis, and I used deploy to S3, after this I change deploy to my server. And this can use different options: rsync or sftp.

**Comment by glushchenko** [comment]
Yep, deployment overhead:

content - travis - s3/sftp

vs

content - s3/sftp

**Comment by Juev** [comment]
I think you have another problem: your micropress placed config file in HOME directory. And travis cannot to use this config file. 

Ok, I don't have more questions. Thank you!
